services:

  pg_runaterrans:
    image: postgres:latest
    container_name: pg_runaterrans
    restart: always
    environment:
      POSTGRES_USER: jonasaray
      POSTGRES_DB: runaterrans
      POSTGRES_PASSWORD: jaray1234
      POSTGRES_ROOT_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./database/CREATE.SQL:/docker-entrypoint-initdb.d/create_data.sql
    ports:
      - "5433:5432"

  #! Forma de llenar la base de datos con las tablas
  #? sudo docker cp database/CREATE.SQL <conteinerName>:<Ruta>     
  #? sudo docker exec -it <conteinerID> bash
  #? psql -U postgres -d runaterrans < CREATE.SQL

  web_api_nest_runaterrans:
    container_name: web_api_nest_runaterrans
    image: web_api_nest_runaterrans
    build: 
      context: .
      dockerfile: DOCKERFILE
    restart: always
    depends_on: 
      - pg_runaterrans
    ports:
      - "3000:3000"
    

volumes:
  #web_data:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: ./postgres-data
      o: bind
